name: Tutor_CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Execute bootstrap.sh to install dependencies(flake8 and pytest included)
      run: |
        pip3 install pipenv
        export PIPENV_VENV_IN_PROJECT="enabled"
        export VIRTUALENV_ALWAYS_COPY=1
        pipenv sync --dev
        sudo -u postgres createdb tutor
        sudo -u postgres psql -c "ALTER ROLE postgres WITH PASSWORD 'tutor';"
    - name: Lint with flake8
      run: |
        flake8 . --count --select=W291,W292,W293,E3,E9 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pipenv run python3 -m pytest
