name: Tutor_CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: tutor
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies(flake8 and pytest included)
      run: |
        sudo apt update
        sudo apt install postgresql postgresql-contrib postgresql-common postgresql-client
        pip3 install pipenv
        pipenv sync --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8 . --count --select=W291,W292,W293,E3,E9 --show-source --statistics
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pipenv run python3 -m pytest
